export const QUIZ_CONFIG = {
  SCHOOL_NAME: "SEAT OF WISDOM COMPREHENSIVE COLLEGE",
  COLLABORATORS: "MATHEMATICS CLUB IN COLLABORATION WITH STEM CLUB",
  EVENT_TITLE: "2025/2026 SECOND TERM MATHOPEDIA",
  TOTAL_QUESTIONS: 40,
  DEFAULT_TIME: 90, // 1 minute 30 seconds
};